spring:
  application:
    name: main-service

  sql:
    init:
      mode: always

  profiles:
    active: ${MAIN_ACTIVE_PROFILE}

  output:
    ansi:
      enabled: ALWAYS

logging:
  file:
    name: ./mainLogs
