server:
  port: ${MAIN_SERVICE_PORT}
rate-service:
  base:
    url: ${RATE_SERVICE_BASE_URL}
  api:
    key: ${RATE_SERVICE_API_KEY}
    passphrase: ${RATE_SERVICE_API_PASSPHRASE}
spring:
  datasource:
    url: jdbc:${POSTGRES_PROVIDER}://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USERNAME}
    driver-class-name: ${DRIVER_CLASS_NAME}
api:
  key: ${API_KEY}
  passphrase: ${API_PASSPHRASE}


