server:
  port: ${SERVER-PORT}
rate-service:
  base:
    url: ${RATE-SERVICE_BASE_URL}
  api:
    key: ${RATE-SERVICE-API-KEY}
    passphrase: ${RATE-SERVICE-API-PASSPHRASE}
spring:
  datasource:
    url: jdbc:${POSTGRES_PROVIDER}://${POSTGRES_HOST}:${POSTGRES_PORT}/{POSTGRES_DB}
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_PORT}
    driver-class-name: ${DRIVER_CLASS_NAME}
api:
  key: ${API-KEY}
  passphrase: ${api-passphrase}


