# later we would opt for multi-stage for smaller images
FROM openjdk:17-jdk-alpine
#  working dir
WORKDIR /app
# Copy the built JAR file
COPY target/*.jar app.jar
# Expose the port
EXPOSE 8080
CMD ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]
