spring:
   application:
      name: rate-service
   profiles:
      active: ${ACTIVE_PROFILE}

springdoc:
   info:
      title: Rate Service API
      description: API for fetching exchange rates
      version: 1.0.0
      contact:
         name: Your Name
         email: your.email@example.com
         url: http://your-website.com
      license:
         name: Apache 2.0
         url: http://www.apache.org/licenses/LICENSE-2.0.html