spring:
   application:
      name: rate-service

   profiles:
      active: ${ACTIVE_PROFILE}

   output:
      ansi:
         enabled: ALWAYS

springdoc:
   info:
      title: Rate Service API
      description: API for fetching exchange rates
      version: 1.0.0
      contact:
         name: frank mwangi
         email: thetechguy499@gmail.com
         url:
      license:
         name: Apache 2.0
         url: http://www.apache.org/licenses/LICENSE-2.0.html

logging:
   file:
      name: ./log
