#!/bin/bash
set -e

# Load environment variables from .env
if [ -f .env ]; then
  set -o allexport
  source .env
  set +o allexport
else
  echo ".env file not found!"
  exit 1
fi
NAME="$APPLICATION_NAME"
IMAGE="$IMAGE_NAME"
PORT="$SERVER_PORT"
docker build -t "$IMAGE" .
JAVA_OPTS="$JAVA_OPTS -Dspring.profiles.active=$ACTIVE_PROFILE"
docker run -d \
  -p "$PORT:$PORT" \
  -e JAVA_OPTS="$JAVA_OPTS" \
  -e ACTIVE_PROFILE="$ACTIVE_PROFILE" \
  -e EXCHANGE_RATE_IO_API_KEY="$EXCHANGE_RATE_IO_API_KEY" \
  -e EXCHANGE_BASE_URL="$EXCHANGE_BASE_URL" \
  -e CACHE_TTL="$CACHE_TTL" \
  -e CACHE_MAXIMUM_SIZE="$CACHE_MAXIMUM_SIZE" \
  -e CACHE_ENTRY_SCHEDULE_TIME="$CACHE_ENTRY_SCHEDULE_TIME" \
  -e WEBCLIENT_CONNECTION_TIMEOUT="$WEBCLIENT_CONNECTION_TIMEOUT" \
  -e WEBCLIENT_RESPONSE_TIMEOUT="$WEBCLIENT_RESPONSE_TIMEOUT" \
  -e WEBCLIENT_READ_TIMEOUT="$WEBCLIENT_READ_TIMEOUT" \
  -e WEBCLIENT_WRITE_TIMEOUT="$WEBCLIENT_WRITE_TIMEOUT" \
  -e EXCHANGE_RATE_TEST_API_KEY="$EXCHANGE_RATE_TEST_API_KEY" \
  --name "$NAME" \
  "$IMAGE"

  docker logs -f $name
